# Generated by Django 3.1.2 on 2021-06-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='imgUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
