# Generated by Django 3.2.4 on 2021-07-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cart_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cartQty',
            field=models.IntegerField(default=0),
        ),
    ]
