# Generated by Django 3.2.4 on 2021-07-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_profile_cartqty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllProducts',
            new_name='AllProduct',
        ),
    ]
