# Generated by Django 3.2.4 on 2021-07-12 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210708_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='paymentId',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
