# Generated by Django 3.2.4 on 2021-07-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_orderpending_ps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpending',
            name='paymentId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
