# Generated by Django 3.2.4 on 2021-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_orderpending_paymentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='slipTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
